### ISSUE TITLE
Need to choose Unicode for tiles

### ISSUE THREAD

**Issue by iltimasd** [iltimasd/andmatebot-test#1]
Goal: choose Unicode for tiles that create the most amount of alignment.

There is one constant and the chess pieces. after that there are a handful of unicodes that could be used from black tiles. and a handful whitespaces. See file 'UnicodeCanidates.md' : https://github.com/iltimasd/andmatebot-test/blob/c2ca6257131ea9dcb7d21121793cc2780e7d38b6/unicodeCanidates.md

**Comment by juliamullen** [comment]
I like the Large White Square + Large Black Square for two reasons:
1. I think for best alignment we should choose "dual" icons for black and white.
2. I think having an all emoji chessboard is cute

**Comment by iltimasd** [comment]
![chess alignment](https://cloud.githubusercontent.com/assets/20071081/16710357/4eb8f3d8-45f9-11e6-8fd0-65db4e8fbe08.PNG)

these are the code points that have the same width as a chess piece

**Comment by iltimasd** [comment]
okay we could use emojis. if we replace ':piece:' with ':piece:+:space:' theres a small amount of misalignment
 and drop tweeting the FEN as precautionary measure

**Comment by iltimasd** [comment]
I have had success with Windows+Chrome twitter displaying an aligned board using black and white square emojis, u2B1C and u2B1B as tiles and padding pieces with  u200A and a standard space

⬜⬛⬜⬛⬜ ♝ ⬜⬛
⬛⬜⬛⬜⬛⬜⬛⬜
⬜⬛⬜ ♗ ⬜⬛⬜⬛
 ♙  ♟  ♟ ⬜⬛⬜ ♚ ⬜
⬜⬛ ♜ ⬛⬜⬛ ♟ ⬛
⬛⬜⬛ ♟ ⬛⬜⬛ ♖ 
⬜⬛⬜⬛ ♝  ♙ ⬜⬛
⬛⬜ ♛ ⬜ ♔ ⬜⬛⬜

Which means we might have to revert to replaces.

**Comment by iltimasd** [comment]
EDIT: this is most likely overkill/adding too many variables for alignment

We could add numbers and and letters to the sides, as coordinate labeling. This would open up the potential for using spaces as tiles. but pushes on our char count:

_worst case scenario, no pieces have been captured.  

with 32 blank tiles and 32 pieces, and 16 letters and number. if the pieces need padding then the character total formula is:

32tiles + #ofRemainingPieces*(1+#ofCharForPadding) + 16coorodinatesChar

so with no pieces captured, and padding is 2(1 on each side)

32 + 32*(1+2) +16 = 144

meaning, with this setup, at least 2 pieces need to be capture. low threshold imo._

EDIT: realized its 17 for coorChar, as there needs to be a space for the x-axis labelling to be aligned. which would mean we need a space at the beginning, BUT we could put the labels on the bottom.

**Comment by iltimasd** [comment]
^so yeh overkill probs but!

good to think about worst case scenario char

Formula:   140 - Tiles with no pieces + # of pieces*(1 + # of padding chars) = extra chars
WCS:        140 - 32 + 32(1+2)= 12

**Comment by iltimasd** [comment]
whoops accidently closed

**Comment by iltimasd** [comment]
okay so i think padding with u200A and standard space is the trick.

So that means we need to figure out how to map a single char to 3. 

And to add a bit that if that if there is a piece in A1, the piece should have all its padding flushed right.
EDITTTTTT: SOOO the code point U+2060, word joiner, is a zero-width whitespace without a WSpace=Y that is NOT rejected by twitter, so we can just throw that at the front of the chessboard if A1 is a non-tile
