### ISSUE TITLE
First char of tweet is ignored if whitespace

### ISSUE THREAD

**Issue by iltimasd** [iltimasd/andmatebot-test#3]
All boards have white in the upper left corner, so the first char needs to represent that,

this is a related issue to issue #1

**Comment by iltimasd** [comment]
Maybe we could use an emoticon like ☐ to represent white tiles

**Comment by juliamullen** [comment]
this is a non-issue if we represent the tiles without pieces as icons, which I think would have to be the case (because of this issue).
